spring:
  profiles:
    active:
    - dev
    
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost
#    username: postgres
#    password: 
#    driver-class-name: org.postgresql.Driver
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
#      hibernate.format_sql: true  
